### ISSUE TITLE
群红包可否加个黑名单或者白名单

### ISSUE THREAD

**Issue by yamei333** [kagg886/QQRedPackGetter#1]
RT, 要是什么群都抢, 那可不得把你当脚本直接一jo踢出群 (失礼了, 哈哈
最好再能加一个开关, 关闭的时候不监听消息 (防止一不小心当红包超人)

※过年那段时间, 正好在玩relink, 红包疯狂错过, 看到这个插件也是觉得自己发现晚了....

**Comment by kagg886** [comment]
pull request welcome :D
~~才不是因为自己对electron不熟悉什么的哼唧~~

**Comment by yamei333** [comment]
~完了, 我也是菜鸡...~
~不然先丢着吧, 真闲得蛋疼的时候再去其他项目品一下代码看看能不能偷些什么~

**Comment by kagg886** [comment]
黑名单已添加
