### ISSUE TITLE
qq红包提示：[QQ红包]请使用新版手机QQ查收红包。

### ISSUE THREAD

**Issue by renwuqiang** [kagg886/QQRedPackGetter#16]
pc上 qq红包提示：[QQ红包]请使用新版手机QQ查收红包。
导致无法自动抢红包。qqnt已是最新版。
有什么解决办法吗

**Comment by kagg886** [comment]
这得等电脑qq更新以支持这种红包消息（

本插件是基于dom点击而不是协议发包的
