### ISSUE TITLE
我想提交代码

### ISSUE THREAD

**Issue by JoeNKin** [kagg886/QQRedPackGetter#2]
我增加了 _包含关键词不领红包_ 和 _取消必须打开你想监听的群窗口这个限制_
**指定窗口不领取** 和 **管理员不领取** 这个功能只需要加几行就行（我懒了 
更的代码做到了不破坏现有代码 另建redPackfindObserver函数
请问如何提交代码

**Comment by kagg886** [comment]
1. fork该项目
2. clone你fork的项目，修改代码
3. 提交commit，push
4. 打开Pull Requests，发起拉取请求

感谢贡献！
