### ISSUE TITLE
是setting.json而非config.json

### ISSUE THREAD

**Issue by QingXuer** [kagg886/QQRedPackGetter#8]

**Comment by kagg886** [comment]
这样，你把项目fork了，然后在readme.md里把config改成setting软件给我交个pr

**Comment by QingXuer** [comment]
> 这样，你把项目fork了，然后在readme.md里把config改成setting软件给我交个pr



> 这样，你把项目fork了，然后在readme.md里把config改成setting软件给我交个pr

好的，我试试（

**Comment by QingXuer** [comment]
> 这样，你把项目fork了，然后在readme.md里把config改成setting软件给我交个pr

提交pr了（
